<Project>
  <PropertyGroup>
    <Configurations>Alpha;Debug;Beta;Release</Configurations>
    <JanitorBuildNumberFile>$(MSBuildThisFileDirectory)build-number.txt</JanitorBuildNumberFile>
    <JanitorBuildNumberOverridden Condition="'$(BuildNumber)' != ''">true</JanitorBuildNumberOverridden>
    <BuildNumber Condition="'$(BuildNumber)' == '' and Exists('$(JanitorBuildNumberFile)')">$([System.IO.File]::ReadAllText('$(JanitorBuildNumberFile)').Trim())</BuildNumber>
    <BuildNumber Condition="'$(BuildNumber)' == ''">0</BuildNumber>
    <BuildDate Condition="'$(BuildDate)' == ''">$([System.DateTime]::UtcNow.ToString("yyyy.M.d"))</BuildDate>
    <BuildType Condition="'$(BuildType)' == '' and '$(Configuration)' == ''">Debug</BuildType>
    <BuildType Condition="'$(BuildType)' == ''">$(Configuration)</BuildType>

    <Version>$(BuildDate).$(BuildNumber)</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Alpha' Or '$(Configuration)' == 'Beta'">
    <Optimize>true</Optimize>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
  </PropertyGroup>
</Project>
