<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RedFox.Compression.LZ4" Version="2026.9.27.2" />
    <PackageReference Include="RedFox.GameExtraction" Version="2026.9.27.2" />
    <PackageReference Include="RedFox.GameExtraction.Hashing" Version="2026.9.27.2" />
    <PackageReference Include="RedFox.Graphics3D" Version="2026.9.27.2" />
    <PackageReference Include="RedFox.Graphics3D.Formats" Version="2026.9.27.2" />
    <PackageReference Include="RedFox.Imaging" Version="2026.9.27.2" />
    <PackageReference Include="RedFox.Imaging.Formats" Version="2026.9.27.2" />
    <PackageReference Include="RedFox.Imaging.Vulkan" Version="2026.9.27.2" />
    <PackageReference Include="RedFox.IO" Version="2026.9.27.2" />
    <PackageReference Include="RedFox.Patterns" Version="2026.9.27.2" />
  </ItemGroup>

</Project>