<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Icon-NoGlow.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Icon-NoGlow.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RedFox.GameExtraction.UI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Janitor.Factory\Janitor.Factory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\assets\Icon.png" Link="Icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
