<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\RedFox\src\cs\RedFox.GameExtraction.UI\RedFox.GameExtraction.UI.csproj" />
    <ProjectReference Include="..\..\..\RedFox\src\cs\RedFox.GameExtraction\RedFox.GameExtraction.csproj" />
    <ProjectReference Include="..\Janitor.Factory\Janitor.Factory.csproj" />
    <ProjectReference Include="..\Janitor\Janitor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Icon\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Icon\Icon-NoGlow.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Icon\Icon-NoGlow.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
